/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryyv
 */
public class frmMain extends javax.swing.JFrame {
jifAddHistorias addhistorias;
jifSearchHistorias searchhistorias;
jifNuevaConsulta nuevaconsulta;
jifNuevaPromocion nuevapromocion;
jifMostrarPromociones mostrarpromociones;
DefaultTableModel cumples;
DefaultTableModel consultas;
Funciones.funciones cnn = new Funciones.funciones();
jifRolMedio rolmedio;
jifRolCompleto rolcompleto;

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        cumples = new DefaultTableModel(null, titulos());
        setCumples();
        consultas = new DefaultTableModel(null, titulos());
        setConsultas();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private String[] titulos() {
        String titulo[] = new String[] {"Fecha", "Paciente"};
        return titulo;
    }
    
    private void setCumples() {
        try {
            String sql = "SELECT f_nacimiento, Concat(apellido_pat, ' ', apellido_mat, ' ', nombres) as 'Paciente' "
                    + "FROM paciente ORDER BY f_nacimiento DESC";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            Object datos[] = new Object[2];
            while (rs.next()) {
                for (int i = 0; i < 2; i++) {
                    datos [i] = rs.getObject(i + 1);
                }
                cumples.addRow(datos);
            }
            rs.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void setConsultas() {
        try {
            String sql = "SELECT consulta.fecha, Concat(apellido_pat, ' ', apellido_mat, ' ', nombres) as 'Paciente' "
                    + "FROM consulta, paciente, historia_clinica WHERE consulta.n_historia = historia_clinica."
                    + "n_historia AND paciente.dni = historia_clinica.dni_paciente";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            Object datos[] = new Object [2];
            while (rs.next()) {
                for (int i = 0; i < 2; i ++) {
                    datos[i] = rs.getObject(i + 1);
                }
                consultas.addRow(datos);
            }
            rs.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lypMain = new javax.swing.JLayeredPane();
        pnNotificaciones = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCumples = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProxConsultas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitAddHistoria = new javax.swing.JMenuItem();
        mitSearchHistoria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mitNuevaConsulta = new javax.swing.JMenuItem();
        mnPromocion = new javax.swing.JMenu();
        mitNuevaPromocion = new javax.swing.JMenuItem();
        mitMostrarPromociones = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mitRolMedio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dental Lawyer");

        lypMain.setBackground(new java.awt.Color(204, 102, 0));
        lypMain.setOpaque(true);

        tbCumples.setModel(cumples);
        jScrollPane1.setViewportView(tbCumples);

        tbProxConsultas.setModel(consultas);
        jScrollPane2.setViewportView(tbProxConsultas);

        javax.swing.GroupLayout pnNotificacionesLayout = new javax.swing.GroupLayout(pnNotificaciones);
        pnNotificaciones.setLayout(pnNotificacionesLayout);
        pnNotificacionesLayout.setHorizontalGroup(
            pnNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        pnNotificacionesLayout.setVerticalGroup(
            pnNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNotificacionesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lypMain.setLayer(pnNotificaciones, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lypMainLayout = new javax.swing.GroupLayout(lypMain);
        lypMain.setLayout(lypMainLayout);
        lypMainLayout.setHorizontalGroup(
            lypMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lypMainLayout.createSequentialGroup()
                .addGap(0, 542, Short.MAX_VALUE)
                .addComponent(pnNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lypMainLayout.setVerticalGroup(
            lypMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnNotificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setOpaque(true);

        jMenu1.setText("Archivo");

        mitSalir.setText("Salir");
        mitSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mitSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Historia Clínica");

        mitAddHistoria.setText("Añadir nueva");
        mitAddHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAddHistoriaActionPerformed(evt);
            }
        });
        jMenu2.add(mitAddHistoria);

        mitSearchHistoria.setText("Buscar");
        mitSearchHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSearchHistoriaActionPerformed(evt);
            }
        });
        jMenu2.add(mitSearchHistoria);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Consultas");

        mitNuevaConsulta.setText("Nueva consulta");
        mitNuevaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNuevaConsultaActionPerformed(evt);
            }
        });
        jMenu4.add(mitNuevaConsulta);

        jMenuBar1.add(jMenu4);

        mnPromocion.setText("Promoción");

        mitNuevaPromocion.setText("Nueva promoción");
        mitNuevaPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNuevaPromocionActionPerformed(evt);
            }
        });
        mnPromocion.add(mitNuevaPromocion);

        mitMostrarPromociones.setText("Mostrar promociones");
        mitMostrarPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitMostrarPromocionesActionPerformed(evt);
            }
        });
        mnPromocion.add(mitMostrarPromociones);

        jMenuBar1.add(mnPromocion);

        jMenu5.setText("Programación médica");

        mitRolMedio.setText("Mostrar rol de PM");
        mitRolMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitRolMedioActionPerformed(evt);
            }
        });
        jMenu5.add(mitRolMedio);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lypMain))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lypMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitAddHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAddHistoriaActionPerformed
        if (addhistorias == null || addhistorias.isClosed()) {
            addhistorias = new jifAddHistorias();
            Dimension ds = lypMain.getSize();
            Dimension fs = addhistorias.getSize();
            lypMain.add(addhistorias);
            addhistorias.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            addhistorias.show();
        }
    }//GEN-LAST:event_mitAddHistoriaActionPerformed

    private void mitSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitSalirActionPerformed

    private void mitSearchHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSearchHistoriaActionPerformed
        if (searchhistorias == null || searchhistorias.isClosed()) {
            searchhistorias = new jifSearchHistorias();
            Dimension ds = lypMain.getSize();
            Dimension fs = searchhistorias.getSize();
            lypMain.add(searchhistorias);
            searchhistorias.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            try {
                searchhistorias.setSelected(true);
                searchhistorias.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            searchhistorias.show();
        }
    }//GEN-LAST:event_mitSearchHistoriaActionPerformed

    private void mitNuevaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNuevaConsultaActionPerformed
        if (nuevaconsulta == null || nuevaconsulta.isClosed()) {
            nuevaconsulta = new jifNuevaConsulta();
            Dimension ds = frmMain.lypMain.getSize();
            Dimension fs = nuevaconsulta.getSize();
            nuevaconsulta.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            frmMain.lypMain.add(nuevaconsulta);
            nuevaconsulta.show();
        }
    }//GEN-LAST:event_mitNuevaConsultaActionPerformed

    private void mitNuevaPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNuevaPromocionActionPerformed
        if (nuevapromocion == null || nuevapromocion.isClosed()) {
            nuevapromocion = new jifNuevaPromocion();
            Dimension ds = frmMain.lypMain.getSize();
            Dimension fs = nuevapromocion.getSize();
            nuevapromocion.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            frmMain.lypMain.add(nuevapromocion);
            nuevapromocion.show();
        }
    }//GEN-LAST:event_mitNuevaPromocionActionPerformed

    private void mitMostrarPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitMostrarPromocionesActionPerformed
        if (mostrarpromociones == null || mostrarpromociones.isClosed()) {
            mostrarpromociones = new jifMostrarPromociones();
            Dimension ds = frmMain.lypMain.getSize();
            Dimension fs = mostrarpromociones.getSize();
            mostrarpromociones.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            frmMain.lypMain.add(mostrarpromociones);
            mostrarpromociones.show();
        }
    }//GEN-LAST:event_mitMostrarPromocionesActionPerformed

    private void mitRolMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitRolMedioActionPerformed
        if (rolmedio == null || rolmedio.isClosed()) {
            rolmedio = new jifRolMedio();
            Dimension ds = frmMain.lypMain.getSize();
            Dimension fs = rolmedio.getSize();
            rolmedio.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            frmMain.lypMain.add(rolmedio);
            rolmedio.show();
            try {
                rolmedio.setSelected(true);
                rolmedio.setMaximum(true);
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_mitRolMedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLayeredPane lypMain;
    private javax.swing.JMenuItem mitAddHistoria;
    private javax.swing.JMenuItem mitMostrarPromociones;
    private javax.swing.JMenuItem mitNuevaConsulta;
    private javax.swing.JMenuItem mitNuevaPromocion;
    private javax.swing.JMenuItem mitRolMedio;
    private javax.swing.JMenuItem mitSalir;
    private javax.swing.JMenuItem mitSearchHistoria;
    private javax.swing.JMenu mnPromocion;
    private javax.swing.JPanel pnNotificaciones;
    private javax.swing.JTable tbCumples;
    private javax.swing.JTable tbProxConsultas;
    // End of variables declaration//GEN-END:variables
}
