/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class jifMostrarPromociones extends javax.swing.JInternalFrame {
DefaultTableModel modelo_promociones;
Funciones.funciones cnn = new Funciones.funciones();
jifNuevaPromocion nuevapromocion;
jifModificarPromocion modificarpromocion;
    
    /**
     * Creates new form jifMostrarPromociones
     */
    public jifMostrarPromociones() {
        modelo_promociones = new DefaultTableModel(null, getPromociones());
        setPromociones();
        initComponents();
    }
    
    private String[] getPromociones() {
        String columnas[] = {"Código", "Nombre", "Fecha de inicio", "Tratamiento", "Descuento", "Vigente"};
        return columnas;
    }
    
    private void setPromociones() {
        try {
            String sql = "SELECT promocion.id_promocion, promocion.nombre, promocion.fecha_inicio, tratamiento.nombre, "
                    + "promocion.descuento, promocion.vigente FROM promocion INNER JOIN tratamiento ON promocion."
                    + "id_tratamiento = tratamiento.id_tratamiento";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            Object datos[] = new Object[6];
            while (rs.next()) {
                for (int i = 0; i < 6; i++) {
                    datos[i] = rs.getObject(i + 1);
                }
                modelo_promociones.addRow(datos);
            }
            rs.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPromociones = new javax.swing.JTable();
        btnNueva = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Lista de promiciones");
        setToolTipText("");

        tbPromociones.setModel(modelo_promociones);
        tbPromociones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPromocionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPromociones);

        btnNueva.setText("Nueva");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNueva)
                    .addComponent(btnModificar)
                    .addComponent(btnBaja))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        if (nuevapromocion == null || nuevapromocion.isClosed()) {
            nuevapromocion = new jifNuevaPromocion();
            Dimension ds = frmMain.lypMain.getSize();
            Dimension fs = nuevapromocion.getSize();
            nuevapromocion.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            frmMain.lypMain.add(nuevapromocion);
            nuevapromocion.show();
        }
    }//GEN-LAST:event_btnNuevaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Realmente desea dar de baja a la promoción seleccionada?",
                "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();
        } else {
            btnNueva.requestFocus();
        }        
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (modificarpromocion == null || modificarpromocion.isClosed()) {
            modificarpromocion = new jifModificarPromocion();
            Dimension ds = frmMain.lypMain.getSize();
            Dimension fs = modificarpromocion.getSize();
            modificarpromocion.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            frmMain.lypMain.add(modificarpromocion);
            modificarpromocion.show();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tbPromocionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPromocionesMouseClicked
        btnModificar.setEnabled(true);
    }//GEN-LAST:event_tbPromocionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNueva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPromociones;
    // End of variables declaration//GEN-END:variables
}
