/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class jifNuevaAlergia extends javax.swing.JInternalFrame {
    DefaultTableModel modelo_alergia;
    DefaultTableModel modelo;
    Funciones.funciones cnn = new Funciones.funciones();

    /**
     * Creates new form jifNuevaalergia
     */
    public jifNuevaAlergia() {
        modelo = new DefaultTableModel(null, getColumna());
        modelo_alergia = new DefaultTableModel(null, getColumna());
        setFilas();
        initComponents();
    }
    
    private String[] getColumna() {
        String columna[] = {"Código", "Alergia"};
        return columna;
    }
    
    private void setFilas() {
        try {
            String sql = "SELECT DISTINCT FORMAT(id_alergia, '000'), nombre FROM alergia ORDER BY id_alergia";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            Object datos[] = new Object[2];
            while (rs.next()) {
                for (int i = 0; i < 2; i++) {
                    datos[i] = rs.getString(i + 1);
                }
                modelo.addRow(datos);
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void setAlergias() {
        try {
            String sql = "SELECT DISTINCT alergia_historia.id_alergia, alergia.nombre FROM alergia, alergia_historia "
                    + "WHERE alergia_historia.id_alergia = alergia.id_alergia AND alergia_historia.n_historia is null";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            Object datos[] = new Object[2];
            while (rs.next()) {
                for (int i = 0; i < 2; i++) {
                    datos [i] = rs.getObject(i + 1);
                }
                modelo_alergia.addRow(datos);
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAlergia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlergias = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setTitle("Alergia");
        setToolTipText("");

        tbAlergias.setModel(modelo);
        jScrollPane1.setViewportView(tbAlergias);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAlergia)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnAgregar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Negocio.daoAlergia_historia obj = new Negocio.daoAlergia_historia();
        int[] filasSelec = tbAlergias.getSelectedRows();
        for (int i = 0; i < filasSelec.length; i ++) {
            obj.setId_Alergia(Integer.parseInt(tbAlergias.getValueAt(i, 0).toString()));
            if (obj.insertarId_alergia() == true) {
                System.out.println("Id_alergia registrado correctamente");
            } else {
                System.out.println("No se pudo ingresar id_alergia");
            }
        }
        jifAddHistorias.tbAlergias.setModel(modelo_alergia);
        setAlergias();
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Negocio.daoAlergia obj = new Negocio.daoAlergia();
        obj.setNombre(txtAlergia.getText());
        if (obj.insertar() == true) {
            JOptionPane.showMessageDialog(rootPane, "Alergia registrada con éxito");
            setFilas();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se consiguió insertar alergia");
            setFilas();
        }
        if (obj.insertar_relacion() == true) {
            JOptionPane.showMessageDialog(rootPane, "Relacion ejecutada con éxito");
            setFilas();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se consiguió relacionar");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAlergias;
    private javax.swing.JTextField txtAlergia;
    // End of variables declaration//GEN-END:variables
}
