/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import java.io.InputStream;
import Funciones.fondoOdontograma;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
/**
 *
 * @author ASUS
 */
public class jifOdontograma extends javax.swing.JInternalFrame {
    public InputStream odontograma = this.getClass().getResourceAsStream("/Recursos/Odontograma.png");
    jifProblemas problemas;

    /**
     * Creates new form jifOdontograma
     */
    public jifOdontograma() {
        initComponents();
        cargarimagen(dtpOdontograma, odontograma);
    }
    
    public void cargarimagen(javax.swing.JDesktopPane jDeskp, InputStream fileImagen) {
        try {
            BufferedImage image = ImageIO.read(fileImagen);
            jDeskp.setBorder(new fondoOdontograma(image));
        } catch (Exception e) {
            System.out.println("Imagen no disponible");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpOdontograma = new javax.swing.JDesktopPane();
        lblLingualTercerMolarSuperiorDerecho = new javax.swing.JLabel();
        lblOclusalTercerMolarSuperiorDerecho = new javax.swing.JLabel();
        lblDistalTercerMolarSuperiorDerecho = new javax.swing.JLabel();
        lblLingualSegundoMolarSuperiorDerecho = new javax.swing.JLabel();
        lblOclusalSegundoMolarSuperiorDerecho = new javax.swing.JLabel();
        lblDistalSegundoMolarSuperiorDerecho = new javax.swing.JLabel();
        lblLingualPrimerMolarSuperiorDerecho = new javax.swing.JLabel();
        lblOclusalPrimerMolarSuperiorDerecho = new javax.swing.JLabel();
        lblDistalPrimeMolarSuperiorDerecho = new javax.swing.JLabel();
        lblLingualSegundoPremolarSuperiorDerecho = new javax.swing.JLabel();
        lblDistalSegundoPremolarSuperiorDerecho = new javax.swing.JLabel();
        lblOclusalSegundoPremolarSuperiorDerecho = new javax.swing.JLabel();
        lblLingualPrimerPremolarSuperiorDerecho = new javax.swing.JLabel();
        lblOclusalPrimerPremolarSuperiorDerecho = new javax.swing.JLabel();
        lblDistalPrimerPremolarSuperiorDerecho = new javax.swing.JLabel();
        lblLingualCaninoSuperiorDerecho = new javax.swing.JLabel();
        lblVestibularCaninoSuperiorDerecho = new javax.swing.JLabel();
        lblDistalCaninoSuperiorDerecho = new javax.swing.JLabel();
        lblLingualIncisivoLateralSuperiorDerecho = new javax.swing.JLabel();
        lblVestibularIncisivoLateralSuperiorDerecho = new javax.swing.JLabel();
        lblDistalIncisivoLateralSuperiorDerecho = new javax.swing.JLabel();
        lblLingualIncisivoCentralSuperiorDerecho = new javax.swing.JLabel();
        lblVestibularIncisivoCentralSuperiorDerecho = new javax.swing.JLabel();
        lblDistalIncisivoCentralSuperiorDerecho = new javax.swing.JLabel();
        lblLingualIncisivoCentralSuperiorIzquierdo = new javax.swing.JLabel();
        lblVestibularIncisivoCentralSuperiorIzquierdo = new javax.swing.JLabel();
        lblDistalIncisivoCentralSuperiorIzquierdo = new javax.swing.JLabel();
        lblLingualIncisivoLateralSuperiorIzquierdo = new javax.swing.JLabel();
        lblVestibularIncisivoLateralSuperiorIzquierdo = new javax.swing.JLabel();
        lblDistalIncisivoLateralSuperiorIzquierdo = new javax.swing.JLabel();
        lblLingualCaninoSuperiorIzquierdo = new javax.swing.JLabel();
        lblVestibularCaninoSuperiorIzquierdo = new javax.swing.JLabel();
        lblDistalCaninoSuperiorIzquierdo = new javax.swing.JLabel();
        lblLingualPrimerPremolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblOclusalPrimerPremolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblDistalPrimerPremolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblLingualSegundoPremolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblOclusalSegundoPremolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblDistalSegundoPremolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblLingualPrimerMolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblOclusalPrimerMolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblDistalPrimerMolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblLingualSegundoMolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblOclusalSegundoMolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblDistalSegundoMolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblLingualTercerMolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblOclusalTercerMolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblDistalTercerMolarSuperiorIzquierdo = new javax.swing.JLabel();
        lblDistalTercerMolarInferiorDerecho = new javax.swing.JLabel();
        lblOclusalTercerMolarInferiorDerecho = new javax.swing.JLabel();
        lblLingualTercerMolarInferiorDerecho = new javax.swing.JLabel();
        lblDistalSegundoMolarInferiorDerecho = new javax.swing.JLabel();
        lblOclusalSegundoMolarInferiorDerecho = new javax.swing.JLabel();
        lblLingualSegundoMolarInferiorDerecho = new javax.swing.JLabel();
        lblDistalPrimerMolarInferiorDerecho = new javax.swing.JLabel();
        lblOclusalPrimerMolarInferiorDerecho = new javax.swing.JLabel();
        lblLingualPrimerMolarInferiorDerecho = new javax.swing.JLabel();
        lblDistalSegundoPremolarInferiorDerecho = new javax.swing.JLabel();
        lblOclusalSegundoPremolarInferiorDerecho = new javax.swing.JLabel();
        lblLingualSegundoPremolarInferiorDerecho = new javax.swing.JLabel();
        lblDistalPrimerPremolarInferiorDerecho = new javax.swing.JLabel();
        lblOclusalPrimerPermolarInferiorDerecho = new javax.swing.JLabel();
        lblLingualPrimerPremolarInferiorDerecho = new javax.swing.JLabel();
        lblDistalCaninoInferiorDerecho = new javax.swing.JLabel();
        lblVestibularCaninoInferiorDerecho = new javax.swing.JLabel();
        lblLingualCaninoInferiorDerecho = new javax.swing.JLabel();
        lblDistalIncisivoLateralInferiorDerecho = new javax.swing.JLabel();
        lblVestibularIncisivoLateralInferiorDerecho = new javax.swing.JLabel();
        lblLingualIncisivoLateralInferiorDerecho = new javax.swing.JLabel();
        lblDistalIncisivoCentralInferiorDerecho = new javax.swing.JLabel();
        lblVestibularIncisivoCentralInferiorDerecho = new javax.swing.JLabel();
        lblLingualIncisivoCentralInferiorDerecho = new javax.swing.JLabel();
        lblDistalIncisivoCentralInferiorIzquierdo = new javax.swing.JLabel();
        lblVestibularIncisivoCentralInferiorIzquierdo = new javax.swing.JLabel();
        lblLingualIncisivoCentralInferiorIzquierdo = new javax.swing.JLabel();
        lblDistalIncisivoLateralInferiorIzquierdo = new javax.swing.JLabel();
        lblVestibularIncisivoLateralInferiorIzquierdo = new javax.swing.JLabel();
        lblLingualIncisivoLateralInferiorIzquierdo = new javax.swing.JLabel();
        lblDistalCaninoInferiorIzquierdo = new javax.swing.JLabel();
        lblVestibularCaninoInferiorIzquierdo = new javax.swing.JLabel();
        lblLingualCaninoInferiorIzquierdo = new javax.swing.JLabel();
        lblDistalPrimerPremolarInferiorIzquierdo = new javax.swing.JLabel();
        lblOclusalPrimerPremolarInferiorIzquierdo = new javax.swing.JLabel();
        lblLingualPrimerPremolarInferiorIzquierdo = new javax.swing.JLabel();
        lblDistalSegundoPremolarInferiorIzquierdo = new javax.swing.JLabel();
        lblOclusalSegundoPremolarInferiorIzquierdo = new javax.swing.JLabel();
        lblLingualSegundoPremolarInferiorIzquierdo = new javax.swing.JLabel();
        lblDistalPrimerMolarInferiorIzquierdo = new javax.swing.JLabel();
        lblOclusalPrimerMolarInferiorIzquierdo = new javax.swing.JLabel();
        lblLingualPrimerMolarInferiorIzquierdo = new javax.swing.JLabel();
        lblDistalSegundoMolarInferiorIzquierdo = new javax.swing.JLabel();
        lblOclusalSegundoMolarInferiorIzquierdo = new javax.swing.JLabel();
        lblLingualSegundoMolarInferiorIzquierdo = new javax.swing.JLabel();
        lblDistalTercerMolarInferiorIzquierdo = new javax.swing.JLabel();
        lblOclusalTercerMolarInferiorIzquierdo = new javax.swing.JLabel();
        lblLingualTercerMolarInferiorIzquierdo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Odontograma");
        setToolTipText("");

        dtpOdontograma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLingualTercerMolarSuperiorDerecho.setToolTipText("3° molar superior derecho");
        dtpOdontograma.add(lblLingualTercerMolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 30, 90));

        lblOclusalTercerMolarSuperiorDerecho.setToolTipText("3° molar superior derecho");
        dtpOdontograma.add(lblOclusalTercerMolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 40, 40));

        lblDistalTercerMolarSuperiorDerecho.setToolTipText("3° molar superior derecho");
        dtpOdontograma.add(lblDistalTercerMolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 40, 30));

        lblLingualSegundoMolarSuperiorDerecho.setToolTipText("2° molar superior derecho");
        dtpOdontograma.add(lblLingualSegundoMolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 40, 90));

        lblOclusalSegundoMolarSuperiorDerecho.setToolTipText("2° molar superior derecho");
        dtpOdontograma.add(lblOclusalSegundoMolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 40, 40));

        lblDistalSegundoMolarSuperiorDerecho.setToolTipText("2° molar superior derecho");
        dtpOdontograma.add(lblDistalSegundoMolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 40, 30));

        lblLingualPrimerMolarSuperiorDerecho.setToolTipText("1° molar superior derecho");
        dtpOdontograma.add(lblLingualPrimerMolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 50, 90));

        lblOclusalPrimerMolarSuperiorDerecho.setToolTipText("1° molar superior derecho");
        dtpOdontograma.add(lblOclusalPrimerMolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 40, 40));

        lblDistalPrimeMolarSuperiorDerecho.setToolTipText("1° molar superior derecho");
        dtpOdontograma.add(lblDistalPrimeMolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 50, 30));

        lblLingualSegundoPremolarSuperiorDerecho.setToolTipText("2° premolar superior derecho");
        dtpOdontograma.add(lblLingualSegundoPremolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 30, 110));

        lblDistalSegundoPremolarSuperiorDerecho.setToolTipText("2° premolar superior derecho");
        dtpOdontograma.add(lblDistalSegundoPremolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 30, 40));

        lblOclusalSegundoPremolarSuperiorDerecho.setToolTipText("2° premolar superior derecho");
        dtpOdontograma.add(lblOclusalSegundoPremolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 30, 40));

        lblLingualPrimerPremolarSuperiorDerecho.setToolTipText("1° premolar superior derecho");
        dtpOdontograma.add(lblLingualPrimerPremolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 40, 120));

        lblOclusalPrimerPremolarSuperiorDerecho.setToolTipText("1° premolar superior derecho");
        dtpOdontograma.add(lblOclusalPrimerPremolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 40, 40));

        lblDistalPrimerPremolarSuperiorDerecho.setToolTipText("1° premolar superior derecho");
        dtpOdontograma.add(lblDistalPrimerPremolarSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 40, 50));

        lblLingualCaninoSuperiorDerecho.setToolTipText("Canino superior derecho");
        dtpOdontograma.add(lblLingualCaninoSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 50, 140));

        lblVestibularCaninoSuperiorDerecho.setToolTipText("Canino superior derecho");
        dtpOdontograma.add(lblVestibularCaninoSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 40, 30));

        lblDistalCaninoSuperiorDerecho.setToolTipText("Canino superior derecho");
        dtpOdontograma.add(lblDistalCaninoSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 50, 50));

        lblLingualIncisivoLateralSuperiorDerecho.setToolTipText("Incisivo lateral superior derecho");
        dtpOdontograma.add(lblLingualIncisivoLateralSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 30, 120));

        lblVestibularIncisivoLateralSuperiorDerecho.setToolTipText("Incisivo lateral superior derecho");
        dtpOdontograma.add(lblVestibularIncisivoLateralSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 40, 30));

        lblDistalIncisivoLateralSuperiorDerecho.setToolTipText("Incisivo lateral superior derecho");
        dtpOdontograma.add(lblDistalIncisivoLateralSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 30, 50));

        lblLingualIncisivoCentralSuperiorDerecho.setToolTipText("Incisivo central superior derecho");
        dtpOdontograma.add(lblLingualIncisivoCentralSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 50, 120));

        lblVestibularIncisivoCentralSuperiorDerecho.setToolTipText("Incisivo central superior derecho");
        dtpOdontograma.add(lblVestibularIncisivoCentralSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 50, 40));

        lblDistalIncisivoCentralSuperiorDerecho.setToolTipText("Incisivo central superior derecho");
        dtpOdontograma.add(lblDistalIncisivoCentralSuperiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 50, 50));

        lblLingualIncisivoCentralSuperiorIzquierdo.setToolTipText("Incisivo central superior izquierdo");
        dtpOdontograma.add(lblLingualIncisivoCentralSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 40, 120));

        lblVestibularIncisivoCentralSuperiorIzquierdo.setToolTipText("Incisivo central superior izquierdo");
        dtpOdontograma.add(lblVestibularIncisivoCentralSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 50, 40));

        lblDistalIncisivoCentralSuperiorIzquierdo.setToolTipText("Incisivo central superior izquierdo");
        dtpOdontograma.add(lblDistalIncisivoCentralSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 50, 50));

        lblLingualIncisivoLateralSuperiorIzquierdo.setToolTipText("Incisivo lateral superior izquierdo");
        dtpOdontograma.add(lblLingualIncisivoLateralSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 40, 120));

        lblVestibularIncisivoLateralSuperiorIzquierdo.setToolTipText("Incisivo lateral superior izquierdo");
        dtpOdontograma.add(lblVestibularIncisivoLateralSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 40, 30));

        lblDistalIncisivoLateralSuperiorIzquierdo.setToolTipText("Incisivo lateral superior izquierdo");
        dtpOdontograma.add(lblDistalIncisivoLateralSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 40, 50));

        lblLingualCaninoSuperiorIzquierdo.setToolTipText("Canino superior izquierdo");
        dtpOdontograma.add(lblLingualCaninoSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 40, 140));

        lblVestibularCaninoSuperiorIzquierdo.setToolTipText("Canino superior izquierdo");
        dtpOdontograma.add(lblVestibularCaninoSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 40, 30));

        lblDistalCaninoSuperiorIzquierdo.setToolTipText("Canino superior izquierdo");
        dtpOdontograma.add(lblDistalCaninoSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 40, 50));

        lblLingualPrimerPremolarSuperiorIzquierdo.setToolTipText("1° premolar superior izquierdo");
        dtpOdontograma.add(lblLingualPrimerPremolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 40, 120));

        lblOclusalPrimerPremolarSuperiorIzquierdo.setToolTipText("1° premolar superior izquierdo");
        dtpOdontograma.add(lblOclusalPrimerPremolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 40, 40));

        lblDistalPrimerPremolarSuperiorIzquierdo.setToolTipText("1° premolar superior izquierdo");
        dtpOdontograma.add(lblDistalPrimerPremolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 40, 40));

        lblLingualSegundoPremolarSuperiorIzquierdo.setToolTipText("2° premolar superior izquierdo");
        dtpOdontograma.add(lblLingualSegundoPremolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 30, 110));

        lblOclusalSegundoPremolarSuperiorIzquierdo.setToolTipText("2° premolar superior izquierdo");
        dtpOdontograma.add(lblOclusalSegundoPremolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 30, 40));

        lblDistalSegundoPremolarSuperiorIzquierdo.setToolTipText("2° premolar superior izquierdo");
        dtpOdontograma.add(lblDistalSegundoPremolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 30, 40));

        lblLingualPrimerMolarSuperiorIzquierdo.setToolTipText("1° molar superior izquierdo");
        dtpOdontograma.add(lblLingualPrimerMolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 50, 100));

        lblOclusalPrimerMolarSuperiorIzquierdo.setToolTipText("1° molar superior izquierdo");
        dtpOdontograma.add(lblOclusalPrimerMolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 50, 40));

        lblDistalPrimerMolarSuperiorIzquierdo.setToolTipText("1° molar superior izquierdo");
        dtpOdontograma.add(lblDistalPrimerMolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 50, 30));

        lblLingualSegundoMolarSuperiorIzquierdo.setToolTipText("2° molar superior izquierdo");
        dtpOdontograma.add(lblLingualSegundoMolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 40, 90));

        lblOclusalSegundoMolarSuperiorIzquierdo.setToolTipText("2° molar superior izquierdo");
        dtpOdontograma.add(lblOclusalSegundoMolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 40, 40));

        lblDistalSegundoMolarSuperiorIzquierdo.setToolTipText("2° molar superior izquierdo");
        dtpOdontograma.add(lblDistalSegundoMolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 40, 30));

        lblLingualTercerMolarSuperiorIzquierdo.setToolTipText("3° molar superior izquierdo");
        dtpOdontograma.add(lblLingualTercerMolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 40, 90));

        lblOclusalTercerMolarSuperiorIzquierdo.setToolTipText("3° molar superior izquierdo");
        dtpOdontograma.add(lblOclusalTercerMolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 40, 40));

        lblDistalTercerMolarSuperiorIzquierdo.setToolTipText("3° molar superior izquierdo");
        dtpOdontograma.add(lblDistalTercerMolarSuperiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 40, 40));

        lblDistalTercerMolarInferiorDerecho.setToolTipText("3° molar inferior derecho");
        dtpOdontograma.add(lblDistalTercerMolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 40, 40));

        lblOclusalTercerMolarInferiorDerecho.setToolTipText("3° molar inferior derecho");
        dtpOdontograma.add(lblOclusalTercerMolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 40, 40));

        lblLingualTercerMolarInferiorDerecho.setToolTipText("3° molar inferior derecho");
        dtpOdontograma.add(lblLingualTercerMolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 50, 80));

        lblDistalSegundoMolarInferiorDerecho.setToolTipText("2° molar inferior derecho");
        dtpOdontograma.add(lblDistalSegundoMolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 50, 40));

        lblOclusalSegundoMolarInferiorDerecho.setToolTipText("2° molar inferior derecho");
        dtpOdontograma.add(lblOclusalSegundoMolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 40, 40));

        lblLingualSegundoMolarInferiorDerecho.setToolTipText("2° molar inferior derecho");
        dtpOdontograma.add(lblLingualSegundoMolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 50, 100));

        lblDistalPrimerMolarInferiorDerecho.setToolTipText("1° molar inferior derecho");
        dtpOdontograma.add(lblDistalPrimerMolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 50, 40));

        lblOclusalPrimerMolarInferiorDerecho.setToolTipText("1° molar inferior derecho");
        dtpOdontograma.add(lblOclusalPrimerMolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 50, 40));

        lblLingualPrimerMolarInferiorDerecho.setToolTipText("1° molar inferior derecho");
        dtpOdontograma.add(lblLingualPrimerMolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 50, 110));

        lblDistalSegundoPremolarInferiorDerecho.setToolTipText("2° premolar inferior derecho");
        dtpOdontograma.add(lblDistalSegundoPremolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 40, 40));

        lblOclusalSegundoPremolarInferiorDerecho.setToolTipText("2° premolar inferior derecho");
        dtpOdontograma.add(lblOclusalSegundoPremolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 40, 40));

        lblLingualSegundoPremolarInferiorDerecho.setToolTipText("2° premolar inferior derecho");
        dtpOdontograma.add(lblLingualSegundoPremolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 40, 110));

        lblDistalPrimerPremolarInferiorDerecho.setToolTipText("1° premolar inferior derecho");
        dtpOdontograma.add(lblDistalPrimerPremolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 40, 40));

        lblOclusalPrimerPermolarInferiorDerecho.setToolTipText("1° premolar inferior derecho");
        dtpOdontograma.add(lblOclusalPrimerPermolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 30, 40));

        lblLingualPrimerPremolarInferiorDerecho.setToolTipText("1° premolar inferior derecho");
        dtpOdontograma.add(lblLingualPrimerPremolarInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 40, 110));

        lblDistalCaninoInferiorDerecho.setToolTipText("Canino inferior derecho");
        dtpOdontograma.add(lblDistalCaninoInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 40, 50));

        lblVestibularCaninoInferiorDerecho.setToolTipText("Canino inferior derecho");
        dtpOdontograma.add(lblVestibularCaninoInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 40, 40));

        lblLingualCaninoInferiorDerecho.setToolTipText("Canino inferior derecho");
        dtpOdontograma.add(lblLingualCaninoInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 40, 120));

        lblDistalIncisivoLateralInferiorDerecho.setToolTipText("Incisivo lateral inferior derecho");
        dtpOdontograma.add(lblDistalIncisivoLateralInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 30, 50));

        lblVestibularIncisivoLateralInferiorDerecho.setToolTipText("Incisivo lateral inferior derecho");
        dtpOdontograma.add(lblVestibularIncisivoLateralInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 30, 40));

        lblLingualIncisivoLateralInferiorDerecho.setToolTipText("Incisivo lateral inferior derecho");
        dtpOdontograma.add(lblLingualIncisivoLateralInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 30, 130));

        lblDistalIncisivoCentralInferiorDerecho.setToolTipText("Incisivo central inferior derecho");
        dtpOdontograma.add(lblDistalIncisivoCentralInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 40, 40));

        lblVestibularIncisivoCentralInferiorDerecho.setToolTipText("Incisivo central inferior derecho");
        dtpOdontograma.add(lblVestibularIncisivoCentralInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 40, 40));

        lblLingualIncisivoCentralInferiorDerecho.setToolTipText("Incisivo central inferior derecho");
        dtpOdontograma.add(lblLingualIncisivoCentralInferiorDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 20, 110));

        lblDistalIncisivoCentralInferiorIzquierdo.setToolTipText("Incisivo central inferior izquierdo");
        dtpOdontograma.add(lblDistalIncisivoCentralInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 40, 40));

        lblVestibularIncisivoCentralInferiorIzquierdo.setToolTipText("Incisivo central inferior izquierdo");
        dtpOdontograma.add(lblVestibularIncisivoCentralInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 40, 40));

        lblLingualIncisivoCentralInferiorIzquierdo.setToolTipText("Incisivo central inferior izquierdo");
        dtpOdontograma.add(lblLingualIncisivoCentralInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 30, 110));

        lblDistalIncisivoLateralInferiorIzquierdo.setToolTipText("Incisivo lateral inferior izquierdo");
        dtpOdontograma.add(lblDistalIncisivoLateralInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 30, 50));

        lblVestibularIncisivoLateralInferiorIzquierdo.setToolTipText("Incisivo lateral inferior izquierdo");
        dtpOdontograma.add(lblVestibularIncisivoLateralInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 30, 40));

        lblLingualIncisivoLateralInferiorIzquierdo.setToolTipText("Incisivo lateral inferior izquierdo");
        dtpOdontograma.add(lblLingualIncisivoLateralInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 30, 130));

        lblDistalCaninoInferiorIzquierdo.setToolTipText("Canino inferior izquierdo");
        dtpOdontograma.add(lblDistalCaninoInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 30, 40));

        lblVestibularCaninoInferiorIzquierdo.setToolTipText("Canino inferior izquierdo");
        dtpOdontograma.add(lblVestibularCaninoInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 40, 40));

        lblLingualCaninoInferiorIzquierdo.setToolTipText("Canino inferior izquierdo");
        dtpOdontograma.add(lblLingualCaninoInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 30, 130));

        lblDistalPrimerPremolarInferiorIzquierdo.setToolTipText("1° premolar inferior izquierdo");
        dtpOdontograma.add(lblDistalPrimerPremolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 40, 40));

        lblOclusalPrimerPremolarInferiorIzquierdo.setToolTipText("1° premolar inferior izquierdo");
        dtpOdontograma.add(lblOclusalPrimerPremolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 30, 40));

        lblLingualPrimerPremolarInferiorIzquierdo.setToolTipText("1° premolar inferior izquierdo");
        dtpOdontograma.add(lblLingualPrimerPremolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 40, 110));

        lblDistalSegundoPremolarInferiorIzquierdo.setToolTipText("2° premolar inferior izquierdo");
        dtpOdontograma.add(lblDistalSegundoPremolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 40, 40));

        lblOclusalSegundoPremolarInferiorIzquierdo.setToolTipText("2° premolar inferior izquierdo");
        dtpOdontograma.add(lblOclusalSegundoPremolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 40, 40));

        lblLingualSegundoPremolarInferiorIzquierdo.setToolTipText("2° premolar inferior izquierdo");
        dtpOdontograma.add(lblLingualSegundoPremolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 40, 110));

        lblDistalPrimerMolarInferiorIzquierdo.setToolTipText("1° molar inferior izquierdo");
        dtpOdontograma.add(lblDistalPrimerMolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 50, 40));

        lblOclusalPrimerMolarInferiorIzquierdo.setToolTipText("1° molar inferior izquierdo");
        dtpOdontograma.add(lblOclusalPrimerMolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 50, 40));

        lblLingualPrimerMolarInferiorIzquierdo.setToolTipText("1° molar inferior izquierdo");
        dtpOdontograma.add(lblLingualPrimerMolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 50, 110));

        lblDistalSegundoMolarInferiorIzquierdo.setToolTipText("2° molar inferior izquierdo");
        dtpOdontograma.add(lblDistalSegundoMolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 50, 40));

        lblOclusalSegundoMolarInferiorIzquierdo.setToolTipText("2° molar inferior izquierdo");
        dtpOdontograma.add(lblOclusalSegundoMolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 40, 40));

        lblLingualSegundoMolarInferiorIzquierdo.setToolTipText("2° molar inferior izquierdo");
        dtpOdontograma.add(lblLingualSegundoMolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 50, 100));

        lblDistalTercerMolarInferiorIzquierdo.setToolTipText("3° molar inferior izquierdo");
        dtpOdontograma.add(lblDistalTercerMolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 50, 40));

        lblOclusalTercerMolarInferiorIzquierdo.setToolTipText("3° molar inferior izquierdo");
        dtpOdontograma.add(lblOclusalTercerMolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 40, 40));

        lblLingualTercerMolarInferiorIzquierdo.setToolTipText("3° molar inferior izquierdo");
        dtpOdontograma.add(lblLingualTercerMolarInferiorIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 50, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Odontograma.png"))); // NOI18N
        dtpOdontograma.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpOdontograma, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dtpOdontograma)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtpOdontograma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDistalCaninoInferiorDerecho;
    private javax.swing.JLabel lblDistalCaninoInferiorIzquierdo;
    private javax.swing.JLabel lblDistalCaninoSuperiorDerecho;
    private javax.swing.JLabel lblDistalCaninoSuperiorIzquierdo;
    private javax.swing.JLabel lblDistalIncisivoCentralInferiorDerecho;
    private javax.swing.JLabel lblDistalIncisivoCentralInferiorIzquierdo;
    private javax.swing.JLabel lblDistalIncisivoCentralSuperiorDerecho;
    private javax.swing.JLabel lblDistalIncisivoCentralSuperiorIzquierdo;
    private javax.swing.JLabel lblDistalIncisivoLateralInferiorDerecho;
    private javax.swing.JLabel lblDistalIncisivoLateralInferiorIzquierdo;
    private javax.swing.JLabel lblDistalIncisivoLateralSuperiorDerecho;
    private javax.swing.JLabel lblDistalIncisivoLateralSuperiorIzquierdo;
    private javax.swing.JLabel lblDistalPrimeMolarSuperiorDerecho;
    private javax.swing.JLabel lblDistalPrimerMolarInferiorDerecho;
    private javax.swing.JLabel lblDistalPrimerMolarInferiorIzquierdo;
    private javax.swing.JLabel lblDistalPrimerMolarSuperiorIzquierdo;
    private javax.swing.JLabel lblDistalPrimerPremolarInferiorDerecho;
    private javax.swing.JLabel lblDistalPrimerPremolarInferiorIzquierdo;
    private javax.swing.JLabel lblDistalPrimerPremolarSuperiorDerecho;
    private javax.swing.JLabel lblDistalPrimerPremolarSuperiorIzquierdo;
    private javax.swing.JLabel lblDistalSegundoMolarInferiorDerecho;
    private javax.swing.JLabel lblDistalSegundoMolarInferiorIzquierdo;
    private javax.swing.JLabel lblDistalSegundoMolarSuperiorDerecho;
    private javax.swing.JLabel lblDistalSegundoMolarSuperiorIzquierdo;
    private javax.swing.JLabel lblDistalSegundoPremolarInferiorDerecho;
    private javax.swing.JLabel lblDistalSegundoPremolarInferiorIzquierdo;
    private javax.swing.JLabel lblDistalSegundoPremolarSuperiorDerecho;
    private javax.swing.JLabel lblDistalSegundoPremolarSuperiorIzquierdo;
    private javax.swing.JLabel lblDistalTercerMolarInferiorDerecho;
    private javax.swing.JLabel lblDistalTercerMolarInferiorIzquierdo;
    private javax.swing.JLabel lblDistalTercerMolarSuperiorDerecho;
    private javax.swing.JLabel lblDistalTercerMolarSuperiorIzquierdo;
    private javax.swing.JLabel lblLingualCaninoInferiorDerecho;
    private javax.swing.JLabel lblLingualCaninoInferiorIzquierdo;
    private javax.swing.JLabel lblLingualCaninoSuperiorDerecho;
    private javax.swing.JLabel lblLingualCaninoSuperiorIzquierdo;
    private javax.swing.JLabel lblLingualIncisivoCentralInferiorDerecho;
    private javax.swing.JLabel lblLingualIncisivoCentralInferiorIzquierdo;
    private javax.swing.JLabel lblLingualIncisivoCentralSuperiorDerecho;
    private javax.swing.JLabel lblLingualIncisivoCentralSuperiorIzquierdo;
    private javax.swing.JLabel lblLingualIncisivoLateralInferiorDerecho;
    private javax.swing.JLabel lblLingualIncisivoLateralInferiorIzquierdo;
    private javax.swing.JLabel lblLingualIncisivoLateralSuperiorDerecho;
    private javax.swing.JLabel lblLingualIncisivoLateralSuperiorIzquierdo;
    private javax.swing.JLabel lblLingualPrimerMolarInferiorDerecho;
    private javax.swing.JLabel lblLingualPrimerMolarInferiorIzquierdo;
    private javax.swing.JLabel lblLingualPrimerMolarSuperiorDerecho;
    private javax.swing.JLabel lblLingualPrimerMolarSuperiorIzquierdo;
    private javax.swing.JLabel lblLingualPrimerPremolarInferiorDerecho;
    private javax.swing.JLabel lblLingualPrimerPremolarInferiorIzquierdo;
    private javax.swing.JLabel lblLingualPrimerPremolarSuperiorDerecho;
    private javax.swing.JLabel lblLingualPrimerPremolarSuperiorIzquierdo;
    private javax.swing.JLabel lblLingualSegundoMolarInferiorDerecho;
    private javax.swing.JLabel lblLingualSegundoMolarInferiorIzquierdo;
    private javax.swing.JLabel lblLingualSegundoMolarSuperiorDerecho;
    private javax.swing.JLabel lblLingualSegundoMolarSuperiorIzquierdo;
    private javax.swing.JLabel lblLingualSegundoPremolarInferiorDerecho;
    private javax.swing.JLabel lblLingualSegundoPremolarInferiorIzquierdo;
    private javax.swing.JLabel lblLingualSegundoPremolarSuperiorDerecho;
    private javax.swing.JLabel lblLingualSegundoPremolarSuperiorIzquierdo;
    private javax.swing.JLabel lblLingualTercerMolarInferiorDerecho;
    private javax.swing.JLabel lblLingualTercerMolarInferiorIzquierdo;
    private javax.swing.JLabel lblLingualTercerMolarSuperiorDerecho;
    private javax.swing.JLabel lblLingualTercerMolarSuperiorIzquierdo;
    private javax.swing.JLabel lblOclusalPrimerMolarInferiorDerecho;
    private javax.swing.JLabel lblOclusalPrimerMolarInferiorIzquierdo;
    private javax.swing.JLabel lblOclusalPrimerMolarSuperiorDerecho;
    private javax.swing.JLabel lblOclusalPrimerMolarSuperiorIzquierdo;
    private javax.swing.JLabel lblOclusalPrimerPermolarInferiorDerecho;
    private javax.swing.JLabel lblOclusalPrimerPremolarInferiorIzquierdo;
    private javax.swing.JLabel lblOclusalPrimerPremolarSuperiorDerecho;
    private javax.swing.JLabel lblOclusalPrimerPremolarSuperiorIzquierdo;
    private javax.swing.JLabel lblOclusalSegundoMolarInferiorDerecho;
    private javax.swing.JLabel lblOclusalSegundoMolarInferiorIzquierdo;
    private javax.swing.JLabel lblOclusalSegundoMolarSuperiorDerecho;
    private javax.swing.JLabel lblOclusalSegundoMolarSuperiorIzquierdo;
    private javax.swing.JLabel lblOclusalSegundoPremolarInferiorDerecho;
    private javax.swing.JLabel lblOclusalSegundoPremolarInferiorIzquierdo;
    private javax.swing.JLabel lblOclusalSegundoPremolarSuperiorDerecho;
    private javax.swing.JLabel lblOclusalSegundoPremolarSuperiorIzquierdo;
    private javax.swing.JLabel lblOclusalTercerMolarInferiorDerecho;
    private javax.swing.JLabel lblOclusalTercerMolarInferiorIzquierdo;
    private javax.swing.JLabel lblOclusalTercerMolarSuperiorDerecho;
    private javax.swing.JLabel lblOclusalTercerMolarSuperiorIzquierdo;
    private javax.swing.JLabel lblVestibularCaninoInferiorDerecho;
    private javax.swing.JLabel lblVestibularCaninoInferiorIzquierdo;
    private javax.swing.JLabel lblVestibularCaninoSuperiorDerecho;
    private javax.swing.JLabel lblVestibularCaninoSuperiorIzquierdo;
    private javax.swing.JLabel lblVestibularIncisivoCentralInferiorDerecho;
    private javax.swing.JLabel lblVestibularIncisivoCentralInferiorIzquierdo;
    private javax.swing.JLabel lblVestibularIncisivoCentralSuperiorDerecho;
    private javax.swing.JLabel lblVestibularIncisivoCentralSuperiorIzquierdo;
    private javax.swing.JLabel lblVestibularIncisivoLateralInferiorDerecho;
    private javax.swing.JLabel lblVestibularIncisivoLateralInferiorIzquierdo;
    private javax.swing.JLabel lblVestibularIncisivoLateralSuperiorDerecho;
    private javax.swing.JLabel lblVestibularIncisivoLateralSuperiorIzquierdo;
    // End of variables declaration//GEN-END:variables
}
