/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import static Presentation.jifFactura.lblConsulta;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryyv
 */
public class jifSearchConsultas extends javax.swing.JInternalFrame {
DefaultTableModel modelo_dni;
DefaultTableModel modelo_nombre;
Funciones.funciones cnn = new Funciones.funciones();
JIFNuevoPaciente historia;
jifFactura factura;

    /**
     * Creates new form jifShowHistorias
     */
    public jifSearchConsultas() {
        modelo_dni = new DefaultTableModel(null, getColumnad());
        modelo_nombre = new DefaultTableModel(null, getColumnan());
        setFilas();
        initComponents();
    }
    private String[] getColumnad() {
        String columna[] = new String[] {"Consulta", "DNI", "Paciente", "Celular", "Lugar de procedencia"};
        return columna;
    }
    
    private String[] getColumnan() {
        String columna[] = {"Consulta", "DNI", "Paciente", "Celular", "Lugar de procedencia"};
        return columna;
    }
    
    private void setFilas() {
        try {
            String sql = "SELECT consulta.id_consulta, paciente.dni, CONCAT(paciente.apellido_pat, ' ', paciente.apellido_mat, ' ', "
                    + "paciente.nombres) AS 'Paciente', paciente.cel1, lugar_procedencia.nombre AS "
                    + "'Lugar de procedencia' FROM paciente INNER JOIN lugar_procedencia ON "
                    + "lugar_procedencia.id_procedencia = paciente.id_procedencia INNER JOIN historia_clinica ON "
                    + "paciente.dni = historia_clinica.dni_paciente INNER JOIN consulta ON historia_clinica.n_historia = "
                    + "consulta.n_historia";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            Object datos[] = new Object[5];
            while (rs.next()) {
                for (int i = 0; i < 5; i++) {
                    datos [i] = rs.getObject(i + 1);
                }
                modelo_dni.addRow(datos);
                modelo_nombre.addRow(datos);
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpHistorias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbHistoriasDNI = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHistoriasNom = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Buscar consulta");
        setAutoscrolls(true);

        tbpHistorias.setFocusable(false);

        jPanel1.setAutoscrolls(true);
        jPanel1.setFocusable(false);

        jLabel1.setText("Escriba un DNI para buscar");
        jLabel1.setFocusable(false);

        txtDni.setNextFocusableComponent(btnGuardar);
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDniKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDniKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });

        tbHistoriasDNI.setModel(modelo_dni);
        tbHistoriasDNI.setFocusable(false);
        tbHistoriasDNI.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tbHistoriasDNI);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
        );

        tbpHistorias.addTab("Por DNI", jPanel1);

        jPanel2.setFocusable(false);

        jLabel2.setText("Escriba un nombre para buscar");
        jLabel2.setFocusable(false);

        txtNombres.setNextFocusableComponent(btnGuardar);
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombresKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });

        tbHistoriasNom.setModel(modelo_nombre);
        tbHistoriasNom.setFocusable(false);
        tbHistoriasNom.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tbHistoriasNom);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
        );

        tbpHistorias.addTab("Por apellidos", jPanel2);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
            .addComponent(tbpHistorias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpHistorias)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar_dni(String texto) {
        try {
            String [] titulos = {"Consulta", "DNI", "Paciente", "Celular", "Lugar de procedencia"};
            String sql = "SELECT consulta.id_consulta, paciente.dni, CONCAT(paciente.apellido_pat, ' ', paciente.apellido_mat, ' ', "
                    + "paciente.nombres) AS 'Paciente', paciente.cel1, lugar_procedencia.nombre AS "
                    + "'Lugar de procedencia' FROM paciente INNER JOIN lugar_procedencia ON "
                    + "lugar_procedencia.id_procedencia = paciente.id_procedencia INNER JOIN historia_clinica ON "
                    + "paciente.dni = historia_clinica.dni_paciente INNER JOIN consulta ON historia_clinica.n_historia = "
                    + "consulta.n_historia WHERE paciente.dni LIKE '" + texto + "%'";
            System.out.println(sql);
            DefaultTableModel modelo_dni = new DefaultTableModel(null,titulos);
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            String [] fila = new String[5];
            while(rs.next()) {
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getString(i + 1);
                }
                modelo_dni.addRow(fila);
            }
            tbHistoriasDNI.setModel(modelo_dni);
            rs.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void buscar_nombres(String texto) {
        try {
            String [] titulos = {"Consulta", "DNI", "Paciente", "Celular", "Lugar de procedencia"};
            String sql = "SELECT consulta.id_consulta, paciente.dni, CONCAT(paciente.apellido_pat, ' ', paciente.apellido_mat, ' ', "
                    + "paciente.nombres) AS 'Paciente', paciente.cel1, lugar_procedencia.nombre AS "
                    + "'Lugar de procedencia' FROM paciente INNER JOIN lugar_procedencia ON "
                    + "lugar_procedencia.id_procedencia = paciente.id_procedencia INNER JOIN historia_clinica ON "
                    + "paciente.dni = historia_clinica.dni_paciente INNER JOIN consulta ON historia_clinica.n_historia = "
                    + "consulta.n_historia WHERE CONCAT(paciente.apellido_pat, ' ', "
                    + "paciente.apellido_mat, ' ', paciente.nombres) LIKE '" + texto + "%'";
            System.out.println(sql);
            DefaultTableModel modelo_nombre = new DefaultTableModel (null, titulos);
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            String[] fila = new String[5];
            while (rs.next()) {
                for (int i = 0; i < 5; i++) {
                    fila [i] = rs.getString(i + 1);
                }
                modelo_nombre.addRow(fila);
            }
            tbHistoriasNom.setModel(modelo_nombre);
            rs.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
        String text = txtDni.getText();
        buscar_dni(text);
    }//GEN-LAST:event_txtDniKeyTyped

    private void txtDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyReleased
        String text = txtDni.getText();
        buscar_dni(text);
    }//GEN-LAST:event_txtDniKeyReleased

    private void txtDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyPressed
        String text = txtDni.getText();
        buscar_dni(text);
    }//GEN-LAST:event_txtDniKeyPressed

    private void txtNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyPressed
        String text = txtNombres.getText();
        buscar_nombres(text);
    }//GEN-LAST:event_txtNombresKeyPressed

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        String text = txtNombres.getText();
        buscar_nombres(text);
    }//GEN-LAST:event_txtNombresKeyReleased

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        String text = txtNombres.getText();
        buscar_nombres(text);
    }//GEN-LAST:event_txtNombresKeyTyped

    private void cargar_paciente(String dni) {
        try {
            String sql = "SELECT paciente.apellido_pat, paciente.apellido_mat, paciente.nombres FROM paciente WHERE "
                    + "paciente.dni = '" + dni + "'";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                factura.txtApellidoPat.setText(rs.getString(1));
                factura.txtApellidoMat.setText(rs.getString(2));
                factura.txtNombres.setText(rs.getString(3));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Negocio.daoConsulta objConsulta = new Negocio.daoConsulta();
        switch (tbpHistorias.getSelectedIndex()) {
            case 0:
                factura.txtDni.setText(tbHistoriasDNI.getValueAt(tbHistoriasDNI.getSelectedRow(), 1).toString());
                cargar_paciente(tbHistoriasDNI.getValueAt(tbHistoriasDNI.getSelectedRow(), 1).toString());
                factura.txtDni.setEnabled(false);
                factura.txtApellidoPat.setEnabled(false);
                factura.txtApellidoMat.setEnabled(false);
                factura.txtNombres.setEnabled(false);
                factura.txtCuotas.requestFocus();
                factura.lblConsulta.setText(tbHistoriasDNI.getValueAt(tbHistoriasDNI.getSelectedRow(), 0).toString());
                factura.lblConsulta.setVisible(false);
                objConsulta.setId_consulta(Integer.parseInt(lblConsulta.getText()));
                factura.txtSaldo.setText(objConsulta.consultar_saldo(txtDni.getText()));
                factura.txtTotal.setText(objConsulta.consultar_total());
                dispose();
            case 1:
                factura.txtDni.setText(tbHistoriasNom.getValueAt(tbHistoriasNom.getSelectedRow(), 1).toString());
                cargar_paciente(tbHistoriasNom.getValueAt(tbHistoriasNom.getSelectedRow(), 1).toString());
                factura.txtDni.setEnabled(false);
                factura.txtApellidoPat.setEnabled(false);
                factura.txtApellidoMat.setEnabled(false);
                factura.txtNombres.setEnabled(false);
                factura.txtCuotas.requestFocus();
                factura.lblConsulta.setText(tbHistoriasNom.getValueAt(tbHistoriasNom.getSelectedRow(), 0).toString());
                factura.lblConsulta.setVisible(false);
                objConsulta.setId_consulta(Integer.parseInt(lblConsulta.getText()));
                factura.txtSaldo.setText(objConsulta.consultar_saldo(txtDni.getText()));
                factura.txtTotal.setText(objConsulta.consultar_total());
                dispose();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable tbHistoriasDNI;
    public static javax.swing.JTable tbHistoriasNom;
    private javax.swing.JTabbedPane tbpHistorias;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
